# Generated by Django 4.1.7 on 2023-03-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_arcinfo_wi1_alter_arcinfo_wi2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch', models.CharField(blank=True, max_length=200, null=True)),
                ('cu', models.CharField(blank=True, max_length=200, null=True)),
                ('me', models.CharField(blank=True, max_length=200, null=True)),
                ('do', models.CharField(blank=True, max_length=200, null=True)),
                ('emp', models.CharField(blank=True, max_length=200, null=True)),
                ('provide', models.CharField(blank=True, max_length=200, null=True)),
                ('work', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
                ('custom', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.CharField(blank=True, max_length=200, null=True)),
                ('tech', models.CharField(blank=True, max_length=200, null=True)),
                ('each', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('works', models.CharField(blank=True, max_length=200, null=True)),
                ('does', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq1', models.CharField(blank=True, max_length=200, null=True)),
                ('eq2', models.CharField(blank=True, max_length=200, null=True)),
                ('eq3', models.CharField(blank=True, max_length=200, null=True)),
                ('eq4', models.CharField(blank=True, max_length=200, null=True)),
                ('eq5', models.CharField(blank=True, max_length=200, null=True)),
                ('eq6', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(blank=True, max_length=200, null=True)),
                ('first', models.CharField(blank=True, max_length=200, null=True)),
                ('wor', models.CharField(blank=True, max_length=200, null=True)),
                ('hand', models.CharField(blank=True, max_length=200, null=True)),
                ('hazr', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(blank=True, max_length=200, null=True)),
                ('ent', models.CharField(blank=True, max_length=200, null=True)),
                ('par', models.CharField(blank=True, max_length=200, null=True)),
                ('sto', models.CharField(blank=True, max_length=200, null=True)),
                ('mac', models.CharField(blank=True, max_length=200, null=True)),
                ('cus', models.CharField(blank=True, max_length=200, null=True)),
                ('toi', models.CharField(blank=True, max_length=200, null=True)),
                ('cli', models.CharField(blank=True, max_length=200, null=True)),
                ('ser', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(blank=True, max_length=200, null=True)),
                ('t2', models.CharField(blank=True, max_length=200, null=True)),
                ('t3', models.CharField(blank=True, max_length=200, null=True)),
                ('t4', models.CharField(blank=True, max_length=200, null=True)),
                ('t5', models.CharField(blank=True, max_length=200, null=True)),
                ('t6', models.CharField(blank=True, max_length=200, null=True)),
                ('t7', models.CharField(blank=True, max_length=200, null=True)),
                ('t8', models.CharField(blank=True, max_length=200, null=True)),
                ('t9', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ce', models.CharField(blank=True, max_length=200, null=True)),
                ('cl', models.CharField(blank=True, max_length=200, null=True)),
                ('th', models.CharField(blank=True, max_length=200, null=True)),
                ('sp', models.CharField(blank=True, max_length=200, null=True)),
                ('sys', models.CharField(blank=True, max_length=200, null=True)),
                ('plan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
