# Generated by Django 4.1.7 on 2023-03-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_documentation_equipment_requirements_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='provide',
        ),
    ]
